version: '3'
services:
    webserver:
        build:
          context: .
          dockerfile: server/nginx/Dockerfile
        container_name: 'webserver-Hr-Roster'
        restart: 'always'
        links:
          - phpfpm
          - hr_db
        ports:
          - "7000:80"
        volumes:
          - ./www:/var/www/html/
          - ./server/nginx/config/site.conf:/etc/nginx/conf.d/default.conf
          - ./logs/nginx/error.log:/var/log/nginx/error.log
          - ./logs/nginx/access.log:/var/log/nginx/access.log
        networks:
          - code-network

    phpfpm:
        build:
            context: .
            dockerfile: server/php/Dockerfile
        container_name: php-Hr-Roster
        ports:
            - "9000:9000"
        volumes:
            - ./www:/var/www/html/
            - ./server/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - code-network

    hr_db:
     container_name: mysql
     build:
       context: .
       dockerfile: server/mysql/docker/Dockerfile
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: '12345'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: '12345'
       MYSQL_DATABASE: 'hr_platform'
     ports:
       - 6034:3306

networks:
    code-network:
        driver: bridge
