version: '3.7'

services:
  web:
    container_name: ${APP_NAME}_web
    depends_on:
      - db
    build:
      context: ./docker/web
    restart: 'always'
    ports:
      - 9000:80
    volumes:
      - ./:/var/www/app
  db:
    container_name: ${APP_NAME}_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'immap'
      MYSQL_DATABASE: 'todo_docker'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '12345'
    ports:
      - 6033:3306
